export const PROF_BODIES = [
  { id:"acca", label:"ACCA (Association of Chartered Certified Accountants)", category:"Accounting" },
  { id:"boraqs", label:"BORAQS (Board of Registration of Architects & QS)", category:"Engineering" },
  { id:"cipr", label:"CIPR (Chartered Institute of Public Relations)", category:"Communications" },
  { id:"ebk", label:"EBK (Engineers Board of Kenya)", category:"Engineering" },
  { id:"icpak", label:"ICPAK (Institute of Certified Public Accountants)", category:"Accounting" },
  { id:"ics", label:"ICS (Institute of Certified Secretaries)", category:"Admin" },
  { id:"ihrm", label:"IHRM (Institute of Human Resource Management)", category:"HR" },
  { id:"iek", label:"IEK (Institution of Engineers of Kenya)", category:"Engineering" },
  { id:"iia", label:"IIA (Institute of Internal Auditors)", category:"Audit" },
  { id:"isaca", label:"ISACA (Information Systems Audit & Control Association)", category:"Audit" },
  { id:"isk", label:"ISK (Institution of Surveyors of Kenya)", category:"Engineering" },
  { id:"kcpa", label:"KCPA (Kenya Counselling & Psychological Association)", category:"Social Services" },
  { id:"kim", label:"KIM (Kenya Institute of Management)", category:"Management" },
  { id:"kism", label:"KISM (Kenya Institute of Supplies Management)", category:"Supply Chain" },
  { id:"kmlttb", label:"KMLTTB (Kenya Medical Lab Technicians & Technologists Board)", category:"Health" },
  { id:"kmpdc", label:"KMPDC (Kenya Medical Practitioners & Dentists Council)", category:"Health" },
  { id:"kndi", label:"KNDI (Kenya Nutritionists & Dieticians Institute)", category:"Health" },
  { id:"kvb", label:"KVB (Kenya Veterinary Board)", category:"Health" },
  { id:"lsk", label:"LSK (Law Society of Kenya)", category:"Legal" },
  { id:"mck", label:"MCK (Media Council of Kenya)", category:"Communications" },
  { id:"msk", label:"MSK (Marketing Society of Kenya)", category:"Marketing" },
  { id:"nca", label:"NCA (National Construction Authority)", category:"Engineering" },
  { id:"nck", label:"NCK (Nursing Council of Kenya)", category:"Health" },
  { id:"nema", label:"NEMA (National Environment Management Authority)", category:"Environment" },
  { id:"ppb", label:"PPB (Pharmacy & Poisons Board)", category:"Health" },
  { id:"prsk", label:"PRSK (Public Relations Society of Kenya)", category:"Communications" },
  { id:"tsc", label:"TSC (Teachers Service Commission)", category:"Education" },
  { id:"aak", label:"AAK (Architectural Association of Kenya)", category:"Engineering" },
  { id:"iqsk", label:"IQSK (Institute of Quantity Surveyors of Kenya)", category:"Engineering" },
  { id:"ispak", label:"ISPAK (Institute of Secretaries and Public Administrators of Kenya)", category:"Admin" },
  { id:"iik", label:"IIK (Insurance Institute of Kenya)", category:"Insurance" },
  { id:"actuarial_society_ke", label:"Actuarial Society of Kenya", category:"Finance" },
  { id:"statistical_society_ke", label:"Statistical Society of Kenya", category:"Research" },
  { id:"geological_society_ke", label:"Geological Society of Kenya", category:"Engineering" },
  { id:"geological_board_ke", label:"Geological Board of Kenya", category:"Engineering" },
]