export const PROF_QUALS = [
  { id:"acca", label:"ACCA", category:"Accounting" },
  { id:"advocate", label:"Advocate of the High Court", category:"Legal" },
  { id:"aws", label:"AWS Certification", category:"ICT" },
  { id:"ccna", label:"CCNA (Cisco Certified Network Associate)", category:"ICT" },
  { id:"ccnp", label:"CCNP (Cisco Certified Network Professional)", category:"ICT" },
  { id:"ceh", label:"CEH (Certified Ethical Hacker)", category:"ICT" },
  { id:"cfe", label:"CFE (Certified Fraud Examiner)", category:"Audit" },
  { id:"cfa", label:"CFA (Chartered Financial Analyst)", category:"Finance" },
  { id:"chrp", label:"CHRP (Certified HR Professional)", category:"HR" },
  { id:"cia", label:"CIA (Certified Internal Auditor)", category:"Audit" },
  { id:"cifa", label:"CIFA (Certified Investment & Financial Analyst)", category:"Finance" },
  { id:"cim", label:"CIM (Chartered Institute of Marketing)", category:"Marketing" },
  { id:"cipd", label:"CIPD (Chartered Institute of Personnel & Development)", category:"HR" },
  { id:"cips", label:"CIPS (Chartered Institute of Procurement & Supply)", category:"Supply Chain" },
  { id:"cisa", label:"CISA (Information Systems Auditor)", category:"Audit" },
  { id:"cma", label:"CMA (Certified Management Accountant)", category:"Accounting" },
  { id:"comptia_sec", label:"CompTIA Security+", category:"ICT" },
  { id:"cpa_k", label:"CPA(K)", category:"Accounting" },
  { id:"cps", label:"CPS(K) — Certified Public Secretary", category:"Legal" },
  { id:"cpsp_k", label:"CPSP-K (Certified Procurement & Supply Professional)", category:"Supply Chain" },
  { id:"cra", label:"CRA (Certified Risk Analyst)", category:"Audit" },
  { id:"crisc", label:"CRISC (Certified in Risk & Information Systems Control)", category:"Audit" },
  { id:"crma", label:"CRMA (Certification in Risk Management Assurance)", category:"Audit" },
  { id:"itil", label:"ITIL Certification", category:"ICT" },
  { id:"azure", label:"Microsoft Azure Certification", category:"ICT" },
  { id:"pmp", label:"PMP (Project Management Professional)", category:"Management" },
  { id:"pgdl", label:"Post Graduate Diploma in Law (KSL)", category:"Legal" },
  { id:"pgdhrm", label:"PGDHRM (Post Graduate Diploma in HRM)", category:"HR" },
  { id:"prince2", label:"PRINCE2", category:"Management" },
  { id:"supplies_licence", label:"Supplies Practitioner's Licence (KISM)", category:"Supply Chain" },
  { id:"acii", label:"ACII (Associate in Insurance — London)", category:"Insurance" },
  { id:"aiik", label:"AIIK (Associate of Insurance Institute of Kenya)", category:"Insurance" },
  { id:"iik_diploma", label:"IIK Diploma in Insurance (Kenya)", category:"Insurance" },
  { id:"cissp", label:"CISSP (Certified Information Systems Security Professional)", category:"ICT" },
  { id:"mcse", label:"MCSE (Microsoft Certified Systems Engineer)", category:"ICT" },
  { id:"pgde", label:"PGDE (Post Graduate Diploma in Education)", category:"Education" },
  { id:"crmp", label:"CRMP (Certified Risk Management Professional)", category:"Risk" },
  { id:"frm", label:"FRM (Financial Risk Manager)", category:"Risk" },
  { id:"prm", label:"PRM (Professional Risk Manager)", category:"Risk" },
  { id:"iso_31000", label:"ISO 31000 (Risk Management Certification)", category:"Risk" },
  { id:"iso_37301", label:"ISO 37301 (Compliance Management Certification)", category:"Risk" },
  { id:"ifo_a", label:"IFoA (Institute and Faculty of Actuaries)", category:"Finance" },
]